name: Add issues & pull-requests to projects by label

on:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]

jobs:
  projects:
    uses: rubinius/.github/.github/workflows/projects.yml@main
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
